[workspace]
resolver = "3"
members = ["slvr_rust_lib_build", "slvr_rust_lib_common", "slvr_rust_lib_errors", "slvr_rust_lib_macro", "slvr_rust_lib_errors", "slvr_rust_lib_disjoint_groups"]
exclude = ["slvr_rust_lib_dev"]
